// Side menu
export const OPEN_SIDE_MENU = "OPEN_SIDE_MENU";
export const CLOSE_SIDE_MENU = "CLOSE_SIDE_MENU";

// Share Menu
export const OPEN_SHARE_MODAL = "OPEN_SHARE_MODAL";
export const CLOSE_SHARE_MODAL = "CLOSE_SHARE_MODAL";

// Share Menu
export const OPEN_COMMENT_MODAL = "OPEN_COMMENT_MODAL";
export const CLOSE_COMMENT_MODAL = "CLOSE_COMMENT_MODAL";

//Info window
export const CLOSE_INFO_WINDOW = "CLOSE_INFO_WINDOW";

//language
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE"

//Reaction
export const CLAP_CONTENT = "CLAP_CONTENT";

//Categories
export const START_LOADING_CATEGORIES = "START_LOADING_CATEGORIES";
export const LOAD_CATEGORIES_SUCCESS = "LOAD_CATEGORIES_SUCCESS";
export const LOADING_CATEGORIES_FAIL = "LOADING_CATEGORIES_FAIL";


//Contents
export const START_LOADING_CONTENTS = "START_LOADING_CONTENTS";
export const LOAD_CONTENTS_SUCCESS = "LOAD_CONTENTS_SUCCESS";
export const LOADING_CONTENTS_FAIL = "LOADING_CONTENTS_FAIL";


//Contents
export const START_LOADING_AUTHORS = "START_LOADING_AUTHORS";
export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";
export const LOADING_AUTHORS_FAIL = "LOADING_AUTHORS_FAIL";

